### ISSUE TITLE
Remove artificial limitation to one instance of the driver

### ISSUE THREAD

**Issue by rvoell-gcx** [SiliconLabs/wfx-fullMAC-driver#12]
Currently the driver is designed in a way, which artificial limits the amount of instances of this driver to one. This is caused by the definition of global variables: https://github.com/SiliconLabs/wfx-fullMAC-driver/blob/fd0c623a4fda24862f339a44dd9b3e6534a9ae01/wfx_fmac_driver/sl_wfx.c#L48-L50
It would be nice, if this could be changed, even if this will result into giving the correct context/handle to all functions of the api in sl_wfx.h. Also all functions implemented by the host api could use this context to distinguish between physical instances of the wfx200 chips.
I know, that this might result into no longer compatible api but it would make development of a more generic drivers e.g. for Zephyr much easier.

**Comment by silabs-JulienT** [comment]
Hi, 

Thank you for the input.
We will review your proposal and come back to you.

**Comment by silabs-JulienT** [comment]
Hi, 

We decided to not proceed with your request as it would mean a major driver redesign to only enable a limited number of use cases.
