### ISSUE TITLE
[Question] Does the WF200 and its driver support "Channel Switch Announcement" as host?

### ISSUE THREAD

**Issue by sbithinx** [SiliconLabs/wfx-fullMAC-driver#13]
Hi,
we are using the WF200 in our project and need the optional Wifi feature "Channel Switch Announcement", as described here:

[Invoking Genuine Channel Switch-Announcements in 802.11 Networks](https://github.com/maneshthankappan/Analysis-of-Genuine-Channel-Switch-Announcements-in-802.11-Networks/blob/main/README.md)

Does the WF200 and its driver support "Channel Switch Announcement" as host in the AP mode?

Greetings
Sebastian

**Comment by silabs-JulienT** [comment]
Hi Sebastian,

We don't support the feature through our Full-MAC driver. However, the WF200 supports it through its Low-MAC driver (cf. 
[https://github.com/SiliconLabs/wfx-linux-driver](https://github.com/SiliconLabs/wfx-linux-driver))

**Post-edit:** In the Low-MAC case: 
No CSA support (requiring HW/FW changes) is implemented.
WF200 is robust to a channel switch in STA mode in the sense that it will detect the absence of the BSS, and the above layers will trigger a join on the new channel. Following this, communication will be restored without any user interaction. This takes at least a couple beacon duration (n*102 ms) and is not as fast and seamless as a true CSA (where channel switching can be done in ~1ms)._

Regards,
Julien

**Comment by sbithinx** [comment]
Thanks for the support and quick reply. :-)

Greetings
Sebastian

**Comment by sbithinx** [comment]
Sorry to reopen the ticket, but apparently your official support answered something contrary, as one my colleagues contact them earlier:

```
Original Case Details:

Case #: 00296249
Subject: Channel Switch Announcement
```

> In SoftAP mode, WF200 doesn't support Channel Switch Announcement, and there is no plan to implement this in the future with WF200.
> In STA mode, the STA should follow the external AP announcements.

And apparently, if `iw phy` is executed on our device running yocto, it does not report back, that it is supporting `channel_switch`:

```
root@*:/run# iw phy
Wiphy phy0
    ...
    Supported commands:
		 * new_interface
		 * set_interface
		 * new_key
		 * start_ap
		 * new_station
		 * set_bss
		 * authenticate
		 * associate
		 * deauthenticate
		 * disassociate
		 * join_ibss
		 * remain_on_channel
		 * set_tx_bitrate_mask
		 * frame
		 * frame_wait_cancel
		 * set_wiphy_netns
		 * set_channel
		 * set_wds_peer
		 * tdls_mgmt
		 * tdls_oper
		 * probe_client
		 * set_noack_map
		 * register_beacons
		 * start_p2p_device
		 * set_mcast_rate
		 * connect
		 * disconnect
		 * set_qos_map
		 * set_multicast_to_unicast
```

Could you please explain and maybe give link to the related documentation or source code?

Greetings
Sebastian

**Comment by MarcDorval** [comment]
I post-edited the initial reply with the following text (in order for readers to get the information directly):

In the Low-MAC case:
No CSA support (requiring HW/FW changes) is implemented.
WF200 is robust to a channel switch in STA mode in the sense that it will detect the absence of the BSS, and the above layers will trigger a join on the new channel. Following this, communication will be restored without any user interaction. This takes at least a couple beacon duration (n*102 ms) and is not as fast and seamless as a true CSA (where channel switching can be done in ~1ms).
