### ISSUE TITLE
More permissive license for sl_status.h and firmware?

### ISSUE THREAD

**Issue by thorvald** [SiliconLabs/wfx-fullMAC-driver#5]
Most of the files seem to be Apache 2.0 licensed, which is awesome.
However, `sl_status.h` and the firmware blob are still licensed under the MSLA, which is considerably more restrictive. Any chance of softening the license on these files?

**Comment by silabs-JulienT** [comment]
Hi Thorvald,

Thanks for the interest. We are reviewing an alignment of license policy throughout the driver. I will keep you posted.

Julien

**Comment by silabs-JulienT** [comment]
Hi Thorvald,

The sl_status.h file has been aligned with the Apache license used in the rest of the driver. However, we are still reviewing impacts on the firmware blob as it is coupled with other licenses. 

Julien

**Comment by silabs-JulienT** [comment]
Hi Thorvald, 

The firmware blob license has been updated with less restrictive terms.

Julien
