### ISSUE TITLE
Firmware crash on RSSI read

### ISSUE THREAD

**Issue by m0nka** [SiliconLabs/wfx-fullMAC-driver#8]
Hey,

We use the WF200 chip and see this intermediate firmware crash when we enable constant(every 10s) read of the RSSI via sl_wfx_get_signal_strength(). 

Exception data from the chip:

 4 0 0 0 76 17 0 0 0 0 0 0 0 0 0 0 0 0 0 0 F8 BA 4E 7 0 0 0 0 0 
0 0 0 68 6 59 7 0 2 0 0 0 0 0 0 B1 6 59 7 0 A 0 0 0 0 0 0 B9 6 59 7 0 6 0 0 0 0 
0 0 77 5A 59 7 0 E 0 0 0 0 0 0 10 34 93 A 0 1E F 0 0 0 0 0 11 34 93 A 0 1E 5 0 0
 0 0 0 14 34 93 A 0 1E 2 0 0 0 0 0 16 34 93 A 0 9E 8 0  

The original firmware we have used was 3.3.1, then i have updated to the latest 3.11.1
the crash still persist (only exception data is different). 

Any help will be appreciated. Thank you!

**Comment by m0nka** [comment]
Updated to the latest fmac driver and here the crash dump:

hif: 0: bc 4 e0 a 4 0 0 0 77 17 0 0 0 0 0 0                                     
hif: 10: 0 0 0 0 0 0 0 0 40 66 a2 1 0 e 0 0                                     
hif: 20: 0 0 0 0 47 63 ca 3 0 1e 0 0 0 0 0 0                                    
hif: 30: 49 63 ca 3 0 1e f 0 0 0 0 0 4b 63 ca 3                                 
hif: 40: 0 1e f 0 0 0 0 0 4d 63 ca 3 0 9e 8 0                                   
hif: 50: 0 0 0 0 6c 23 6f 0 0 2 0 0 0 0 0 0                                     
hif: 60: 57 ac 96 1 0 0 0 0 0 0 0 0 9c f7 a0 1                                  
hif: 70: 0 2 0 0 0 0 0 0 e5 f7 a0 1 0 a 0 0                                     
hif: 80: 0 0 0 0 ed f7 a0 1 0 6 0 0 0 0 0 0                                     
hif: 90: 7f a5 c3 3 2 1c 0 0 9 0 0 0 86 a5 c3 3                                 
hif: a0: 2 16 0 0 9 0 1 0 89 a5 c3 3 2 0 0 0                                    
hif: b0: 0 0 0 0 2f aa c3 3 2 2 0 0 0 0 0 0                                     
hif: c0: 33 aa c3 3 2 1c 0 0 1 0 1 0 84 35 c5 3                                 
hif: d0: 2 12 0 0 9 0 1 0 87 35 c5 3 2 1c 0 0                                   
hif: e0: 9 0 0 0 8e 35 c5 3 2 16 0 0 9 0 1 0                                    
hif: f0: 90 35 c5 3 2 0 0 0 0 0 0 0 3c 42 c5 3                                  
hif: 100: 2 2 0 0 0 0 0 0 3f 42 c5 3 2 1c 0 0                                   
hif: 110: 1 0 1 0 89 c5 c6 3 2 12 0 0 9 0 1 0                                   
hif: 120: 8c c5 c6 3 2 1c 0 0 9 0 0 0 93 c5 c6 3                                
hif: 130: 2 16 0 0 9 0 1 0 95 c5 c6 3 2 0 0 0                                   
hif: 140: 0 0 0 0 45 d2 c6 3 2 2 0 0 0 0 0 0                                    
hif: 150: 48 d2 c6 3 2 1c 0 0 1 0 1 0 8f 55 c8 3                                
hif: 160: 2 12 0 0 9 0 1 0 92 55 c8 3 2 1c 0 0                                  
hif: 170: 9 0 0 0 99 55 c8 3 2 16 0 0 9 0 1 0                                   
hif: 180: 9b 55 c8 3 2 0 0 0 0 0 0 0 57 62 c8 3                                 
hif: 190: 2 2 0 0 0 0 0 0 5b 62 c8 3 2 1c 0 0                                   
hif: 1a0: 1 0 1 0 94 e5 c9 3 2 12 0 0 9 0 1 0                                   
hif: 1b0: 96 e5 c9 3 2 1c 0 0 9 0 0 0 9e e5 c9 3                                
hif: 1c0: 2 16 0 0 9 0 1 0 a0 e5 c9 3 2 0 0 0                                   
hif: 1d0: 0 0 0 0 55 2 ca 3 2 2 0 0 0 0 0 0                                     
hif: 1e0: 59 2 ca 3 2 9c 0 0 1 0 1 0 7d a5 c3 3                                 
hif: 1f0: 2 12 0 0 9 0 1 0 77 62 c8 3 3 20 15 9                                 
hif: 200: 0 0 0 1 64 2 ca 3 3 4 0 0 0 0 0 0                                     
hif: 210: 6a 2 ca 3 3 6 0 0 0 0 0 0 75 2 ca 3                                   
hif: 220: 3 a0 1a 9 0 0 0 1 3d aa c3 3 3 4 0 0                                  
hif: 230: 0 0 0 0 43 aa c3 3 3 6 0 0 0 0 0 0                                    
hif: 240: 4f aa c3 3 3 20 6 9 0 0 0 1 4a 42 c5 3                                
hif: 250: 3 4 0 0 0 0 0 0 50 42 c5 3 3 6 0 0                                    
hif: 260: 0 0 0 0 5c 42 c5 3 3 20 b 9 0 0 0 1                                   
hif: 270: 53 d2 c6 3 3 4 0 0 0 0 0 0 59 d2 c6 3                                 
hif: 280: 3 6 0 0 0 0 0 0 64 d2 c6 3 3 20 10 9                                  
hif: 290: 0 0 0 1 65 62 c8 3 3 4 0 0 0 0 0 0                                    
hif: 2a0: 6b 62 c8 3 3 6 0 0 0 0 0 0 4 70 c8 3                                  
hif: 2b0: 5 0 8f 39 44 1 0 0 ee 73 c8 3 5 0 8f 39                               
hif: 2c0: 44 1 0 0 e1 77 c8 3 5 0 8f 39 44 1 0 0                                
hif: 2d0: 9f d1 c8 3 5 0 3 39 44 1 0 0 92 10 c9 3                               
hif: 2e0: 5 0 3 39 44 1 0 0 a0 e7 c9 3 5 0 8f 39                                
hif: 2f0: 44 1 0 0 3e 2 ca 3 5 0 8f 39 44 1 0 0                                 
hif: 300: f0 13 ca 3 5 0 8f 39 44 1 0 0 d7 1a ca 3                              
hif: 310: 5 0 8f 39 44 1 0 0 3c 4c ca 3 5 80 3 39                               
hif: 320: 44 1 0 0 e6 1a ca 3 7 0 80 0 0 0 0 0                                  
hif: 330: eb 1a ca 3 7 84 0 0 0 0 0 0 79 5b c8 3                                
hif: 340: 7 0 80 0 0 0 0 0 7d 5b c8 3 7 4 0 0                                   
hif: 350: 0 0 0 0 52 62 c8 3 7 0 80 0 0 0 0 0                                   
hif: 360: 87 62 c8 3 7 2 0 0 0 0 0 0 1d 69 c8 3                                 
hif: 370: 7 0 80 0 0 0 0 0 21 69 c8 3 7 4 0 0                                   
hif: 380: 0 0 0 0 13 70 c8 3 7 0 80 0 0 0 0 0                                   
hif: 390: 17 70 c8 3 7 4 0 0 0 0 0 0 fb 73 c8 3                                 
hif: 3a0: 7 0 8 42 0 0 0 0 ff 73 c8 3 7 4 0 0                                   
hif: 3b0: 0 0 0 0 ee 77 c8 3 7 0 8 42 0 0 0 0                                   
hif: 3c0: f9 77 c8 3 7 2 0 0 0 0 0 0 af e7 c9 3                                 
hif: 3d0: 7 0 80 0 0 0 0 0 b3 e7 c9 3 7 4 0 0                                   
hif: 3e0: 0 0 0 0 50 2 ca 3 7 0 80 0 0 0 0 0                                    
hif: 3f0: 85 2 ca 3 7 2 0 0 0 0 0 0 0 14 ca 3                                   
hif: 400: 7 0 80 0 0 0 0 0 4 14 ca 3 7 4 0 0                                    
hif: 410: 0 0 0 0 b7 6f e4 1 8 14 0 0 0 0 0 0                                   
hif: 420: 6c 52 e8 1 8 12 0 0 f 0 0 0 5e 72 e8 1                                
hif: 430: 8 14 0 0 0 0 0 0 cf 36 ec 1 8 12 0 0                                  
hif: 440: f 0 0 0 2e 38 ec 1 8 14 0 0 0 0 0 0                                   
hif: 450: 7 23 f0 1 8 12 0 0 f 0 0 0 ca 3a f0 1                                 
hif: 460: 8 14 0 0 0 0 0 0 39 3b f1 1 8 12 0 0                                  
hif: 470: f 0 0 0 2b 3c f1 1 8 14 0 0 0 0 0 0                                   
hif: 480: 82 7d 0 2 8 12 0 0 f 0 0 0 74 7e 0 2                                  
hif: 490: 8 14 0 0 0 0 0 0 d5 bf f 2 8 12 0 0                                   
hif: 4a0: f 0 0 0 9 d2 f 2 8 94 0 0 0 0 0 0                                     
hif: 4b0: 0 0 0 0 b 0 0 0 0 0 0 0    

Hope this helps

**Comment by silabs-JulienT** [comment]
Hey,

Thanks for the report and the dump. We will look into it.
Could you share the firmware exception reason associated with the trace?

Regards,
Julien

**Comment by silabs-JulienT** [comment]
Hi, 

Looking at the dump, it is most likely an issue on the bus/low level and not something specific to the sl_wfx_get_signal_strength() API. 
To confirm this assumption, you can call the following code after the firmware exception:
`sl_wfx_reg_read_32(SL_WFX_CONFIG_REG_ID, &value32);`
It retrieves the [configuration register ](https://docs.silabs.com/wifi/wf200/rtos/latest/wf200-registers#config-register) in value32. You can check for the 8 first bit for bus error flags.

Regards,
Julien

**Comment by m0nka** [comment]
Hi Julien,

Thank you! I will do that.

K.

**Comment by m0nka** [comment]
Hey Julien,

Sorry for the late reply, but as the issue is intermittent, it was challenging to catch it. The config register value after the crash
is 0x02050200, so no error bit is set i guess ?

BR, K.

**Comment by silabs-JulienT** [comment]
Hi, 

Correct, the bus layer seems fine. When pulling for the RSSI value, I assume the WF200 is connected to a Wi-Fi access point. Is it also simultaneously acting as a softAP?

Regards,
Julien

**Comment by m0nka** [comment]
Hey Julien,

No, it is setup as client and reads RSSI only while connected to an AP. I also had the suspicion that connection is dropped at some point and no notification is issued from low level driver and maybe RSSI request keep on going, but i am connected to very local AP(1 meter away, very strong signal), so maybe not very likely ?

BR, K

**Comment by silabs-JulienT** [comment]
Hi,

We will release a new WF200 firmware release. It is fixing some issues leading to firmware exception. it could address yours.

Regards,
Julien

**Comment by m0nka** [comment]
Hey Julien,

Great, thank you! Keep us posted please.

BR, K

**Comment by silabs-JulienT** [comment]
Hi,

The FMAC driver 3.3.1 release includes the WF200 firmware 3.3.1. The firmware release addresses several issues leading to a firmware exception.

Regards,
Julien

**Comment by m0nka** [comment]
Thanks Julien,

I will try on Monday.

All the best!

**Comment by m0nka** [comment]
Hey,

Sorry for the late update. But we have tested the latest code and it still crashes. So currently we only read RSSI once after connecting to the AP and then just approximate random values (+/- 5 dBm) around the initial value every few seconds to create impression of live indicator. Thank you for your time and support.

Regards, K
