### ISSUE TITLE
Add seperate branch for major version

### ISSUE THREAD

**Issue by Jonas-Meyer97** [SiliconLabs/wfx-fullMAC-driver#9]
Add a seperate branch for major versions like 3.x.x to allow submodules to track only a certain major version.
This would prevent compatibilite problems when the major version is updated on the master banch with imcompatible changes to previous major versions.

**Comment by silabs-JulienT** [comment]
Hi, 

Thanks for the feedback. We will review the request. In the meantime, we recommend to use the repository tags to track stable a software version.

Regards,
Julien
